### ISSUE TITLE
Mod causes player model to be invisible with transparent skins

### ISSUE THREAD

**Issue by kaxonomy** [Sollace/Void-Fog#5]
Usually skins should be black when they have pixels that are completely transparent. This mod instead removes limbs if they don't exist and can make the player unrenderable.

[demonstration uploadable skin](https://user-images.githubusercontent.com/19924741/120406117-56993280-c307-11eb-81ab-7b494b8b703a.png)

What happens when worn and F5 third person is pressed:
![](https://i.imgur.com/xrSy7eC.png)

**Comment by Sollace** [comment]
Sorry, I forgot to get back to this, but this issue has since been fixed in version 1.10.0 of Kirin over here: https://github.com/MineLittlePony/Kirin/commit/8aac40ea9000a2f8c390e09d782ba544259a82a2

The feature that enables transparency on skins is now opt-in by mods, so this issue will only occur when you're using Mine Little Pony.

**Comment by Sollace** [comment]
Release notes for 1.10.0 are over here: https://github.com/MineLittlePony/Kirin/releases/tag/1.10.0 (it's the most recent for 1.18+)
